### ISSUE TITLE
I'm getting a mess when I choose to output Chinese subtitles.

### ISSUE THREAD

**Issue by martjay** [tigros/Whisperer#1]
What encoding do you use for your subtitles? I'm getting a mess when I choose to output Chinese subtitles. Also, why doesn't it automatically delete those .wav files after it finishes extracting the subtitles?

![111111](https://user-images.githubusercontent.com/44982189/226151140-8abd6434-9866-4be5-881b-0327f198a1d5.jpg)

**Comment by martjay** [comment]
Selecting English subtitles is the same mess.

**Comment by tigros** [comment]
fixed

**Comment by martjay** [comment]
> fixed

Thank you man, really amazing tool!
