### ISSUE TITLE
Unsupported Windows version, will now exit.

### ISSUE THREAD

**Issue by ourcubk** [tigros/Whisperer#10]
seems this project only support windows 11? 
Could you update one for windows 10, thanks!

**Comment by tigros** [comment]
that's unexpected unless you don't have a graphics card.

what graphics card do you have?

what does "reg query hklm\SYSTEM\CurrentControlSet\Control\Class\\{4d36e968-e325-11ce-bfc1-08002be10318}" return?

**Comment by ourcubk** [comment]
Running as admin takes no effect.
You mean that I need add "GPU Adapter Memory" firstly in perfmon.exe manually? Will try later.

**Comment by tigros** [comment]
yes in perfmon there's a green +, click that and check the list. I'd be surprised if it's a Chinese issue I think I would have heard complaints from others.

**Comment by tigros** [comment]
btw the perfmon check has no effect on whisperer, just to see if GPU Adapter Memory exists.

it's pretty weird, i made a version to show the error, it saves it to log.txt also.

please replace whisperer.exe and try again, paste contents of log.txt.

thanks.
[whisperer.zip](https://github.com/tigros/Whisperer/files/12099841/whisperer.zip)

**Comment by ourcubk** [comment]
System.InvalidOperationException: 无法加载计数器名称数据，因为从注册表读取的索引“”无效。
   在 System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   在 System.Diagnostics.PerformanceCounterLib.get_NameTable()
   在 System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   在 System.Diagnostics.PerformanceCounterLib.GetCategorySample(String category)
   在 System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category)
   在 System.Diagnostics.PerformanceCounterCategory.GetCounterInstances(String categoryName, String machineName)
   在 whisperer.Form1.initperfcounter()

**Comment by tigros** [comment]
never even heard of LODCTR, good to know!
