### ISSUE TITLE
Is it possible to change/add option for output format?

### ISSUE THREAD

**Issue by friedham** [tigros/Whisperer#12]
Huge thanks for the effort of this amazing program!
Will it be possible add option for output format? Like the plain text version or other, it would be super helpful.
Or maybe there's a way to change output format somewhere?

**Comment by tigros** [comment]
you should get visual studio community edition, that is a super easy thing to change. 

wouldn't that be fun? all you have to do is change --output-srt to one of --output-txt --output-vtt  --output-words 

i could easily add a drop down for that too, but less fun for you.
