### ISSUE TITLE
Remove file extension form the output name

### ISSUE THREAD

**Issue by IgorCulafic** [tigros/Whisperer#14]
I'm having a problem with: `fileName.wav.text` being outputted instead of just: `fileName.txt`. 

Could you add an option to just output `fileName.txt` and an option to only output txt without a timestamp?

Thank you.

**Comment by tigros** [comment]
Yes, .wav are a bit special, i could rename them on completion. What about adding the lang too, like filename.en.txt, filename.fr.txt etc? while i'm at it..

**Comment by tigros** [comment]
that should do it, i snuck a new zip in 2.8 release.

**Comment by IgorCulafic** [comment]
Awesome, thank you.
