### ISSUE TITLE
best model available?

### ISSUE THREAD

**Issue by Geniusssmit** [tigros/Whisperer#15]
which model will make the best subtitles possible?

**Comment by Quidam2k** [comment]
While I'm no expert, I imagine the larger the model the better the results. That's been my experience so far. I use large and haven't felt the need to use bigger.

**Comment by tigros** [comment]
for 1 file sure use large, but for 1000's of files, might take a year or 2.

**Comment by tjesp** [comment]
I find that medium is a good compromise between computing time and errors.
