### ISSUE TITLE
Initial Prompt

### ISSUE THREAD

**Issue by Quidam2k** [tigros/Whisperer#16]
Might it be possible to allow the use of an initial prompt? 

Right now Whisperer is my go-to due to its use of the GPU and ability to batch tasks. Thanks for putting it together.

From noScribe:
"Prompts: The whisper AI can be initialized with a short text-sequence called prompt (see [here for more info](https://platform.openai.com/docs/guides/speech-to-text/prompting)). This will influence the style of the following transcription. I tried to force the AI to include filler words like "uhm" in the transcription by giving it a prompt containing them (like "Umm, let me think like, hmm..."). But this only worked on some occasions (whisper tends to 'forget' the prompt quite quickly). Prompts are language specific and will only be applied if you select a particular language (not 'auto'). You can change or add prompts for other languages in the file "prompt.yml" in the home directory of the app."

**Comment by tigros** [comment]
sorry, gonna have to pass on anything prompt for now, doesn't look like main.exe has the option anyway. 

I wasn't aware of noScribe, interesting, thanks!
