### ISSUE TITLE
Whisperer not working

### ISSUE THREAD

**Issue by RickArcher108** [tigros/Whisperer#18]
I'm on a PC with a PowerColor Fighter AMD Radeon RX 6700 XT Gaming Graphics Card with 12GB GDDR6 Memory. 64-bit operating system, x64-based processor. Windows 11 Home.

I can't get Whisperer to work.  Whisper Desktop works just fine. Using the large language model, it can transcribe a 2 hour audio in about 20 minutes. But I'd really like to be able to achieve batch processing. 

I don't get an error message. About 6 hours ago I started a batch of 17 10-minute mp3s. Whisperer immediately made wav files out of them. The Go button changed to Cancel, But then nothing more has happened. 

I don’t hear my GPU’s fan whirring, which usually happens with Whisper. Any suggestions?

**Comment by tigros** [comment]
i wonder if you have an integrated GPU too? you're right the fans should be revving.
try running these commands from a cmd prompt:

    reg query hklm\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318} /f 00* /k
    reg query hklm\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000 /v HardwareInformation*
    reg query hklm\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0001 /v HardwareInformation*

please copy paste the results.

**Comment by RickArcher108** [comment]
Here’s what I got:

Microsoft Windows [Version 10.0.22621.2215]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Rick Archer New>reg query hklm\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318} /f 00* /k

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0001
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0002
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0003
End of search: 4 match(es) found.

C:\Users\Rick Archer New>reg query hklm\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000 /v HardwareInformation*

End of search: 0 match(es) found.

C:\Users\Rick Archer New>reg query hklm\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0001 /v HardwareInformation*

HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0001
    HardwareInformation.ChipType    REG_BINARY    49006E00740065006C0028005200290020005500480044002000470072006100700068006900630073002000460061006D0069006C0079000000
    HardwareInformation.AdapterString    REG_BINARY    49006E00740065006C00280052002900200055004800440020004700720061007000680069006300730020003600330030000000
    HardwareInformation.DacType    REG_BINARY    49006E007400650072006E0061006C000000
    HardwareInformation.BiosString    REG_BINARY    49006E00740065006C00200056006900640065006F002000420049004F0053000000
    HardwareInformation.MemorySize    REG_BINARY    00000040

I did have a 4mb NVIDA GPU that came with the machine. I’m checking with my computer guy to see if he took that out when he put in the new 12gb one. I know Whisper is using the 12gb one, because performance improved dramatically and I can hear it revving.

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
ok, let's check the other 2:
    
    reg query hklm\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0002 /v HardwareInformation*
    reg query hklm\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0003 /v HardwareInformation*

**Comment by RickArcher108** [comment]
Microsoft Windows [Version 10.0.22621.2215]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Rick Archer New>reg query hklm\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0002 /v HardwareInformation*

HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0002
    HardwareInformation.AdapterString    REG_SZ    NVIDIA GeForce GTX 1050 Ti
    HardwareInformation.BiosString    REG_SZ    Version86.7.39.40.55
    HardwareInformation.ChipType    REG_SZ    NVIDIA GeForce GTX 1050 Ti
    HardwareInformation.DacType    REG_SZ    Integrated RAMDAC
    HardwareInformation.MemorySize    REG_DWORD    0xfff00000
    HardwareInformation.qwMemorySize    REG_QWORD    0x100000000

End of search: 6 match(es) found.

C:\Users\Rick Archer New>reg query hklm\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0003 /v HardwareInformation*

HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0003
    HardwareInformation.ChipType    REG_BINARY    41004D004400200052006100640065006F006E002000470072006100700068006900630073002000500072006F0063006500730073006F0072002000280030007800370033004400460029000000
    HardwareInformation.DacType    REG_BINARY    49006E007400650072006E0061006C00200044004100430028003400300030004D0048007A0029000000
    HardwareInformation.AdapterString    REG_BINARY    41004D004400200052006100640065006F006E00200052005800200036003700300030002000580054000000
    HardwareInformation.BiosString    REG_BINARY    3100310033002D003000300031002D005800300031000000
    HardwareInformation.MemorySize    REG_DWORD    0xfff00000
    HardwareInformation.qwMemorySize    REG_QWORD    0x2ff000000

End of search: 6 match(es) found.

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
I see the problem. The NVidia card is removed right? Looks like software wasn't removed properly, google DDU for a tool to remove NVidia drivers.

A quicker way is to run:

    reg delete hklm\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0002 /v HardwareInformation.qwMemorySize

That would remove a single key in the registry related to the 1050 TI (memory size). It's a  key whisperer is concerned about.

Then try whisperer again.

**Comment by RickArcher108** [comment]
I haven’t heard back from my computer guy as to whether he removed the card, but I just ran a tool to remove Nvidia drivers and it seemed to do so. But now when I try to run Whisperer I get

***@***.***

Whisper still works.

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
i just noticed you have HardwareInformation.AdapterString REG_BINARY ...

it's usually a string not REG_BINARY so that might break GPUmembyproc.exe

in cmd prompt cd to whisperer folder and run GPUmembyproc, is it blank? 

what is ***@***.***? that's in the srt file?

**Comment by RickArcher108** [comment]
I just found the Nvidia card that he removed, so it’s definitely out.

Please clarify this instruction:


in cmd prompt cd to whisperer folder and run GPUmembyproc, is it blank?


Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
what folder whisperer in?

cd means change directory, so in cmd you type "cd /d thefolder" then GPUmembyproc

also make sure NVidia qwMemorySize is gone:

    reg query hklm\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0002 /v HardwareInformation.qwMemorySize

if it's still there

    reg delete hklm\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0002 /v HardwareInformation.qwMemorySize

**Comment by RickArcher108** [comment]
F:\Downloads\Whisperer>GPUmembyproc
'GPUmembyproc' is not recognized as an internal or external command,
operable program or batch file.

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by RickArcher108** [comment]
C:\Users\Rick Archer New>reg query hklm\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0002 /v HardwareInformation.qwMemorySize
ERROR: The system was unable to find the specified registry key or value.

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
in cmd F:\Downloads\Whisperer type dir

please paste that.

**Comment by RickArcher108** [comment]
Like this?

F:\Downloads\Whisperer>dir
Volume in drive F has no label.
Volume Serial Number is 90F3-F2E0

Directory of F:\Downloads\Whisperer

09/01/2023  02:15 PM    <DIR>          .
09/01/2023  02:38 PM    <DIR>          ..
04/19/2023  10:32 AM     3,094,623,691 ggml-large.bin
06/08/2023  04:24 PM             1,489 languageCodez.tsv
06/08/2023  04:24 PM           205,312 main.exe
06/08/2023  04:24 PM           444,928 ObjectListView.dll
06/08/2023  04:24 PM               584 README.md
06/08/2023  04:24 PM           467,456 Whisper.dll
06/08/2023  04:25 PM            25,600 whisperer.exe
06/08/2023  04:24 PM               261 whisperer.exe.config
               8 File(s)  3,095,769,321 bytes
               2 Dir(s)  947,256,123,392 bytes free

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
seems you have an old version, get https://github.com/tigros/Whisperer/releases/download/2.8/Whisperer.zip

unzip replacing those files, try GPUmembyproc again.

**Comment by RickArcher108** [comment]
I think we’re in business. The GPU fan is humming and it’s cranking out srt files! Thank you so much for your help.

***@***.***

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
ok good! strange GPUmembyproc was missing though since it's been there since day 1. I'm guessing YASA (yet another stupid antivirus) cheers!

**Comment by RickArcher108** [comment]
Yes, I discovered that Norton was deleting it and I had to override that and restore it.

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
ya Norton is one of the worst things you could put on a PC.

**Comment by RickArcher108** [comment]
What do you use/recommend?

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
i don't use any, there's a program called dControl to turn off defender completely too. To test a file there's virustotal.com

if you don't trust yourself to not click crazy things, i guess i'd go with Windows defender, but seems to me very easy to avoid, then again i'm a long time programmer.

**Comment by RickArcher108** [comment]
Now another weird thing is happening. I loaded up 51 of them last night before bed. It’s been running all night with the GPU fan whirring loudly, but so far, no VTT files have been generated. Any ideas?


***@***.***

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
Do you mean only the VTT check box is checked and nothing? could be Norton, again. I don't see what else it could be.

**Comment by RickArcher108** [comment]
It finally started cranking them out at about 8:15am and has done the first 10. That was after running all night. So it’s working. Just slow. I think if I had done them one by one with Whisper, it would have gone faster. But it’s nice being able to let it run all night.

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
you could just change the 10 at a time to 1 or 2, or change large model to small or base, they work pretty good and much faster.

**Comment by RickArcher108** [comment]
I want maximum accuracy, so I’d rather have it take longer if need be. I have a team of volunteers proofreading them, and don’t want to add to their burden. Do you think that on average, it’ll do more per hour if I have the “Max at once” setting set to one or two? Can I change that setting while it’s in the middle of a job without messing things up?

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
you can change the max at once anytime, no problem. you might've stumbled on a problem though because it shouldn't have run more than 2 at time no matter what max at once says, it checks free GPU memory etc. 

it gets technical now though to see if there's an issue, i might have to code a logger and things like that for you to test. Maybe  NVidia causing a problem idk.

the speed should be about the same with 1 or 2 and large model, nothing major i don't think. 

It would be good if you could open task manager, go to details and see how many main.exe are running at once. should never be more than 2 for large model.

**Comment by RickArcher108** [comment]
I lowered it down to 2. Here's what I'm seeing in Task Manager:
![Screenshot 2023-09-02 121827](https://github.com/tigros/Whisperer/assets/131281569/856f651c-94d0-4f78-89d7-d983d5770779)

In case you can't see that, it says Whisperer is using 28.7% of my CPU and 121 MB of Memory. It calls that 39% but I don't see how it can be because I have 16GB in the machine and 12GB in the GPU.

My GPU is an AMD, not NVidia.

**Comment by tigros** [comment]
you need to click on the > next to whisperer to see main.exe

i meant your old nvidia card, maybe left over stuff causing weirdness.

but to test boost max at once back up to 10 to see how many main.exe start up.

**Comment by RickArcher108** [comment]
![image](https://github.com/tigros/Whisperer/assets/131281569/f4f03af3-fec1-45bb-aa7c-5e55248a056b)

Boosted up to 10:

![image](https://github.com/tigros/Whisperer/assets/131281569/5b6f1e2a-e7f3-406b-b55f-3d6b8038f385)

It changes every second.

**Comment by tigros** [comment]
ok so leave it like that and check if main.exe count goes over 2-3.

**Comment by RickArcher108** [comment]
Leave it on 10?


Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
yes

**Comment by RickArcher108** [comment]
It stays on two. Does that mean that it doesn’t make any difference whether I have it set to two or ten? Do you think one would be faster in the long run?

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
no difference, only if you see it going wild with many main.exe, that's not good. it's checking available GPU memory and waiting until enough to launch another main.exe.

2 instead of 1 might be slightly faster in the long run.

**Comment by RickArcher108** [comment]
I’ll keep it on 2 for now. It has now processed 39 out of 51 since this morning, after having not completed any overnight even though it was working on them.

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
well to see if there's a bug you need to leave it at 10, if you set it to 2 there's no chance main.exe count will go over 2.

**Comment by RickArcher108** [comment]
I’ve been running it at 10 and checking Task Manager from time to time, and I never see it go over two, but it’s working well, so I’m happy. Probably two is all my machine can handle. I really appreciate your help.

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by tigros** [comment]
ok thanks for running the test, ya large model eats alot of GPU memory, about 4GB each main.exe.
    On Monday, September 4, 2023 at 03:24:40 PM EDT, RickArcher108 ***@***.***> wrote:  
 
 

I’ve been running it at 10 and checking Task Manager from time to time, and I never see it go over two, but it’s working well, so I’m happy. Probably two is all my machine can handle. I really appreciate your help.

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***

**Comment by RickArcher108** [comment]
And I have a 12GB GPU, so three main.exe’s would max it out.

Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***
