### ISSUE TITLE
[suggestion] Can you add a function to show the progress bar and debug console?

### ISSUE THREAD

**Issue by kiron111** [tigros/Whisperer#2]
After the batch transcription launch, I can only use the system monitor to 'guess' the process is working.

And because I may sometime transcribe many files at once, I have to make sure whether the setting is right. 
If I can read the transcription at real time, through the debug console. It would be great for me, just glance for few seconds, and leave the computer alone. (As you know, during the progress, the ventilation fans run loudly and hot air comes out.

**Comment by kiron111** [comment]
Remark:
I have installed avast antivirus, which may block the debug console ( because I have seen the console window pop up once and disappear). 

And in the debug console, the chinese script is not correctly displayed (as the original whisper can show most of the chinese word).

 I don't know if it is only my issue.

**Comment by tigros** [comment]
sorry nope i can't do that, no access to progress etc..
