### ISSUE TITLE
Can't find model.

### ISSUE THREAD

**Issue by boredwithnaming** [tigros/Whisperer#20]
Why can't it find the model? Just like this.
![image](https://github.com/tigros/Whisperer/assets/90591338/80308a2c-d49f-47e2-900e-651a0083b286)
I'm using a Windows10 PC with AMD Ryzen 9 4900H and NVIDIA GeForce RTX 2060, and Whisper Desktop works fine using the same model.

I'm not sure I do understand what you said in the README about ffmpeg. Is this issue related to ffmpeg? But adding ffmpeg to the system environment variables doesn't work either.

I really hope you can help me, because I urgently need to batch process my videos. Thanks!

**Comment by tigros** [comment]
Hi,

That wouldn't make much sense if the file is really there, are you sure it's E:\Downloads?

Can you open cmd and do "dir E:\Downloads"

ffmpeg.exe just needs to be in a folder that's in you PATH variable, in cmd type "path" to see the list.

You can copy ffmpeg.exe to C:\Windows for example.

**Comment by boredwithnaming** [comment]
The results are as follows:
![image](https://github.com/tigros/Whisperer/assets/90591338/38df38e2-dea4-496a-8139-fa1b17f12312)

I am a Chinese, my English is not very good, so I want to make sure that the correct way to use this software is to directly download and unzip Whisperer.zip, then double-click whisperer.exe to use it?Do I need any additional operations?

**Comment by tigros** [comment]
i think maybe the dash "-" in the file name is off, it seems raised, try renaming it with no dash.

the only other operation is getting ffmpeg which you did.

**Comment by boredwithnaming** [comment]
Still not working

**Comment by boredwithnaming** [comment]
It worked. I don't know why it still couldn't find the model when I just removed the "-", but when I renamed the file to "1.bin", it worked.

Anyway, thanks very much for your help, it helps me a lot, and thank you for bringing us such a good project😘

**Comment by tigros** [comment]
it would be better if you named it medium.bin, it looks at that to determine reqd GPU memory.
