### ISSUE TITLE
A weird bug - but I have a video to reproduce it!

### ISSUE THREAD

**Issue by NikosDi** [tigros/Whisperer#22]
Hi again.

Excellent Whisperer v2.9, I managed easily and consistently to reproduce the notorious bug.

I captured it in a video.

How can I send it to you ?

It's ~18 MB video using AV1 codec.

**Comment by tigros** [comment]
don't know what the limit is but 18MB you can surely zip it and drag/drop into a message here.

**Comment by NikosDi** [comment]
I prefer privately

**Comment by tigros** [comment]
try this http://76.65.87.48:8080/myup.html

**Comment by NikosDi** [comment]
Not a problem to upload it somewhere.

I have already uploaded it to my GDrive.

How can I share the link with you ?

**Comment by tigros** [comment]
did the link work? just upload direct.

**Comment by NikosDi** [comment]
Where ?

I could send the link to your email.

**Comment by tigros** [comment]
you don't see this? http://76.65.87.48:8080/myup.html

maybe github blocking?

**Comment by NikosDi** [comment]
Yes, I can see that.

How does that secure privacy ?

**Comment by tigros** [comment]
it's direct to my PC, that's my IP i'll close the port after.

**Comment by NikosDi** [comment]
Done.

The video is self-explanatory, ask me anything here if any questions arise.

**Comment by tigros** [comment]
ok fixed, replaced v2.9

thanks for the video.
