### ISSUE TITLE
Model large-v2 not working?

### ISSUE THREAD

**Issue by ctimict** [tigros/Whisperer#24]
Hello !
Thank you for creating this great tool.
I have a problem with it, I want to use the large-v2 model but it seems the software doesn't work with this model
I use the large model and everything works normally.
Hope you check it out soon and maybe update it again.
Thank you for your contributions!

**Comment by tigros** [comment]
"it can only be attributed to human error" -- HAL 9000

what GPU? maybe not enough vram.

**Comment by ctimict** [comment]
> "nó chỉ có thể gây ra lỗi cho người dùng" -- HAL 9000
> 
> GPU là gì? có lẽ không đủ vram.

I have downloaded both models:
models["large-v2"] here:
https://github.com/openai/whisper/discussions/885
model ggml-large-v1.bin here:
https://huggingface.co/ggerganov/whisper.cpp/tree/main

but both models cannot be used with whisperer.exe.
My computer uses rtx 3060 12gb vram card. I can still use models["large-v2"] with faster-whisper using the command line

**Comment by tigros** [comment]
try ggml-large.bin that's v2
