### ISSUE TITLE
Is it possible to add .lrc extension

### ISSUE THREAD

**Issue by iXi101** [tigros/Whisperer#26]
Because, I want a timestamped output format

**Comment by tigros** [comment]
it's not lyrics format but here's an exe which doesn't remove timestamps from txt type. 
[whisperer.zip](https://github.com/tigros/Whisperer/files/12859985/whisperer.zip)

**Comment by iXi101** [comment]
Thank you very much, I just like the timestamp style of .lrc

[00:10.00] one
[00:12.70] two
[00:18.00] three
...
[mm:ss.xx] end

**Comment by iXi101** [comment]
It doesn’t matter if it’s inconvenient, I found the right software to solve the problem.

https://github.com/SubtitleEdit/subtitleedit
