### ISSUE TITLE
Translation question

### ISSUE THREAD

**Issue by RickArcher108** [tigros/Whisperer#28]
I'm using Whisperer to transcribe hundreds of files that are mostly in English, but in which the speaker will often throw in a little Hindi or Sanskrit. I presume that I should leave "Language" on English. Should I check "Translate to English"? Will it confuse Whisperer if the language is English but it's told to translate to English?

Incidentally, I got a new Dell with a NVIDIA GeForce RTX 4090 24GB GDDR6X in it. My previous computer with a 12GB card strained to run two Whisperers at a time, with fans whirring loudly. Now I'm running 5 at a time and you can barely hear any fan noise.

**Comment by tigros** [comment]
checking translate should be ok, just try both and compare results. i use Beyond Compare, good program for comparing files.

**Comment by RickArcher108** [comment]
Beyond Compare looks useful. What's the difference between the Pro and Standard editions?

**Comment by tigros** [comment]
yes it is very useful, see https://www.scootersoftware.com/kb/feature_compare the green PRO's tells you the differences, standard would be fine.
