### ISSUE TITLE
Meaningless word repetition problem

### ISSUE THREAD

**Issue by kbuwel** [tigros/Whisperer#29]
When a video file over 10 minutes is loaded and converted to srt, txt, etc. using voice recognition, tens of thousands of lines of meaningless words are written.
For example, [end] [baby crying] [everyone] [fire sound], etc.
Words that are not in the video file are written endlessly.
System specifications are as follows:
AMD 5900x
RTX3060 12GB
G.SKILL DDR4 64GB xmp 2.0
870evo 2TB SSD
Too many meaningless words written. Can you solve this problem?

**Comment by tigros** [comment]
this is a known issue, it can happen sometimes, you can search issues in const-me, openai, ggerganov repos, it's all over the place.

maybe in about a year it will finally be resolved.
