### ISSUE TITLE
add a progress bar to handle the prompt?

### ISSUE THREAD

**Issue by samloya** [tigros/Whisperer#3]
Hello, can you add a progress bar to handle the prompt?

**Comment by tigros** [comment]
i tried looking up this --prompt parameter, i'm still confused heh, and what does a progress bar have to do with it?

**Comment by samloya** [comment]
such as this: 

![image_2023-04-10_11-41-26](https://user-images.githubusercontent.com/11858059/230821355-5f98eee5-c25b-4ee8-a460-eb13f6de3f81.png)

**Comment by tigros** [comment]
ok maybe i misunderstood what you meant by prompt, anyway all i could do is count how many processes are running or completed, not the progress of each process, it's just not available. There's a closed issue asking for the same thing, guess i will close this one too, sorry. For example if you run main.exe from command line, there's no mention of progress.
