### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by RickArcher108** [tigros/Whisperer#30]
I'm confused about these different versions. If I just want the latest large model, do I just go for the last one - ggml-large.bin?

![image](https://github.com/tigros/Whisperer/assets/131281569/10cd6e78-c3c4-4e6f-b8d6-61cfc1a6d21f)

Also, I hear there's a new Whisper out. What's the link to that? And how about Whisperer? Is there a new one?

Thanks

**Comment by tigros** [comment]
Hi Rick,

Just keep an eye on const-me's whisper, if he adds support then whisperer can use it.

better not touch any of that for now, keep what you had before.

Cheers!
