### ISSUE TITLE
New version of Whisperer?

### ISSUE THREAD

**Issue by RickArcher108** [tigros/Whisperer#31]
Hi Tigros,

Is there a new version of Whisperer which works with the updated ggml-large.bin? The version I have been using does not.

Thanks,

Rick

**Comment by tigros** [comment]
Hi Rick,

same answer as [#30](https://github.com/tigros/Whisperer/issues/30#issuecomment-1802760472) did you notice v2.9? not v3 compatible but has some minor improvements.

**Comment by RickArcher108** [comment]
Do you mean v2.9 of the ggml-large.bin file? Where can I download that? Sorry, I'm not a programmer and am not as technical as most of the people here, but I'm using Whisperer a lot.

**Comment by tigros** [comment]
v2.9 of whisperer, see [releases](https://github.com/tigros/Whisperer/releases)

**Comment by RickArcher108** [comment]
Got it. And where can I download the earlier version of the ggml-large.bin file? I'm afraid I deleted it when I downloaded v.3

**Comment by tigros** [comment]
try [this](http://198.100.146.225/Downloads/whisper-modes/?sort=d&rev=1)

**Comment by RickArcher108** [comment]
Thanks. I presume that large.bin is newer than large-v1.bin. Right?

**Comment by tigros** [comment]
yes, it's presumably v2.

**Comment by lrq3000** [comment]
Now that emcodem is stopping maintaining the const-me fork, are you considering switching to whisper.cpp by any chance @tigros? Your GUI is awesome! IMHO the most practical to use whisper.

**Comment by tigros** [comment]
it's a shame gonna need different versions for different GPU's, also not sure if const-me version is faster with AMD/Intel GPU's. Someone should run comparison benchmarks for those. Should probably give it a few months to mature anyway.

**Comment by lrq3000** [comment]
Yes it's a shame, it makes things more complicated, but at least there is one project that continues to be maintained in the foreseeable future.

I understand you prefer to let this mature before switching over to another solution, I'm glad you are considering this in the future.

Best regards and i wish you an enjoyable end of the gregorian year!

10 déc. 2023 02:38:44 tigros ***@***.***>:

**Comment by tigros** [comment]
btw i'm pretty sure you can just replace main.exe etc with your preferred whisper.cpp version in the whisperer folder, don't see why not.

**Comment by lrq3000** [comment]
Ah really? I didn't expect they had the same api, i may try to see if i can get whisper 3 to work this way, thanks! (But anyway I'm perfectlu happy with v2 so this is just out of curiosity)

10 déc. 2023 20:28:36 tigros ***@***.***>:
