### ISSUE TITLE
Max at once not working

### ISSUE THREAD

**Issue by JRWSP** [tigros/Whisperer#32]
Hi, 

I tried running 2 copies of the same input file with Whisperer. Even though I use 'Max at once'=2, the program still transcribes the files sequentially and finish with the same time as 'Max at once'=1. 
My GPU is RX 6600M with 8GB of RAM so it should be enough for a small Whisper model.

Why?

**Comment by tigros** [comment]
yes, it should run 2 at a time with small model. From a cmd prompt run GPUmembyproc.exe please post result. 

there is a 10 second delay between launching instances, so short clips would seem sequential.

**Comment by JRWSP** [comment]
For the detail, my testing file is ~18mins long. Picking only 1 file runs ~29s. When picking 2 files and set Max at once = 2 runs ~52s. 

Here is the result from GPUmembyproc.exe
![Screenshot 2023-11-18 142929](https://github.com/tigros/Whisperer/assets/57433713/a13b194e-a2ac-4a0c-962b-c86f3faf1473)

**Comment by tigros** [comment]
looks like GPUmembyproc is having trouble with your PC, it should have printed more, and would explain the issue ur seeing.

try this test version from cmd, please send result.

[GPUmembyproctst.zip](https://github.com/tigros/Whisperer/files/13400599/GPUmembyproctst.zip)

**Comment by JRWSP** [comment]
Now it prints more.

![Screenshot 2023-11-18 155339](https://github.com/tigros/Whisperer/assets/57433713/7fd232be-5a17-4976-a4fe-90370a0dccdf)

**Comment by tigros** [comment]
for some reason the order of GPU's is different on your PC, it's a simple fix.

replace your GPUmembyproc with this one, guess I'll make a new release later on.

[GPUmembyproc.zip](https://github.com/tigros/Whisperer/files/13400881/GPUmembyproc.zip)

**Comment by tigros** [comment]
too small of a change to warrant a new version number, so updated the 2.9 release.
