### ISSUE TITLE
Watch Folders feature

### ISSUE THREAD

**Issue by TDLabs2015** [tigros/Whisperer#34]
Hi, thanks for this work, your app works well so far and is very appreciated! Is it possible that you Could you add the option of a watch folders? so that, certain folders can be  remembered for automatic transcription to take place in the background IF new untranscribed files are  found in the folder? With this I think your app would be almost perfect. Much Thanks already!

**Comment by tigros** [comment]
can you provide a mockup of how it would look based on current version?

**Comment by TDLabs2015** [comment]
Sure, here's possibly what it could look like. you could squeeze some of the setting required into you current UI or maybe make a tab like system, making way for any future additions. Is that ok if not let me know and i can alter it further.

![Whisper UI change](https://github.com/tigros/Whisperer/assets/38634342/87ef8696-9931-4f75-8503-4c964c627486)

**Comment by tigros** [comment]
thanks for that! just curious, what are you doing that requires this, i'd rather not try to imagine and get it wrong.

**Comment by TDLabs2015** [comment]
Transcription is crucial component to a workflow i am building for a "super database". The data is fetched on a daily basis and to have to remember to transcribe things individually will slow things. As it stands your app along with the whisper models has been a godsend! How it can also be useful for others I imagine from my own personal use case. I make a lot of videos with the phone and then save them to folders on my hard drive. To understand what's in this footage takes one to have to watch it or label it at the time. Iphone for example doesn't allow you to add metadata or any detail about the video that was recorded, with auto-transcription and other modern even basic AI assistance tools, very quickly users can gain insights to their footage with a search of the SRT files saving much needed time for one man bands!

**Comment by tigros** [comment]
Hey, I have something for you to try, not exactly like your mockup but i was able to save alot of effort by using some code from my main program, mysys @ integritech.ca

If you want to delete a schedule, click Watch Schedule then cancel, if one exists it will ask if you want to delete it.

Whisperer does not need to be loaded, the Windows scheduler will start it up.

You can view/edit/delete in the Windows scheduler too, it's called Whisperer in there. It calls whisperer.exe with the new /watch command line switch.

Please lemme know how it goes.

Thanks.

[Whispererwatcher.zip](https://github.com/tigros/Whisperer/files/13662862/Whispererwatcher.zip)

**Comment by TDLabs2015** [comment]
Hi Tigros, I just gave it a try again, design looks good, when I make a test schedule, say a minute after i test it, I am met with an error after pressing the Ok button in the schedule popup. Other than that I tried to press "go" to see if this starts transcribing the new watch folder which gets added fine, but nothing happens. Also just downloading your other app to check out look like it's right up my alley!

**Comment by tigros** [comment]
are you using an antivirus? maybe it prevents creating scheduled tasks. try the schedule button in mysys, same thing? it's very similar code..

**Comment by tigros** [comment]
i guess you're right the Go button should process the watch folders so fixed that, also better error message when task save fails so we get a clue. Please try this version.

[Whispererwatcher.zip](https://github.com/tigros/Whisperer/files/13690944/Whispererwatcher.zip)
