### ISSUE TITLE
Whisperer 3.0 - "Skip if output exists" maybe not working

### ISSUE THREAD

**Issue by RickArcher108** [tigros/Whisperer#37]
Hi Tigros, 

I have a folder in which I had completed transcribing about 1,292 of about 1,800 mp3 files using Whisperer 2.9. This morning when I saw v3.0, I cancelled the 2.9 run and started processing the folder with v3.0. But it didn't recognize that 1,292 had been done. It started from scratch. I couldn't tell whether it was overwriting existing vtt files or what. So, I cancelled that job and resumed it using 2.9, and it recognized that 1,292 had been completed and started processing the rest. 

Maybe this feature would have worked if all those files had originally been processed with v3.0. I'll experiment with that once this batch has been completed using 2.9. 

Thanks

**Comment by tigros** [comment]
Hey Rick,

Did you add vtt or something, if any 1 of the checked types don't exist it will redo. On my end seems to work fine.

**Comment by RickArcher108** [comment]
My settings look like this:

![image](https://github.com/tigros/Whisperer/assets/131281569/30fe0970-00bc-4718-b682-a2f793404bac)

That's in v2.9 but they looked the same in v3.0. When I'm finished with this batch, I'll run a batch with v3.0 and see if the problem recurs.

**Comment by RickArcher108** [comment]
I'm afraid v.3 still isn't working for me. It's producing VTT files with nothing in them but the letters WEBVTT. I'm using the ggml-large-v3.bin.

**Comment by tigros** [comment]
it's using same version of whisper as 2.9, so keep using model v2 not v3.

**Comment by RickArcher108** [comment]
Will do. Thanks.
