### ISSUE TITLE
Looks like it does not support large-v3

### ISSUE THREAD

**Issue by erturkdotgg** [tigros/Whisperer#39]
There is an issue with whisperer while using large-v3. When i use v3, it never finishes. It takes forever. But when i use v2, there is no problem.

Also i want to thank you for making this project cuz currently its impossible to find a modification that works with AMD GPU's so this is a life saver.

**Comment by tigros** [comment]
that's right, but if you really need v3 you could replace main.exe etc with [whisper.cpp](https://github.com/ggerganov/whisper.cpp/releases) version, idk if it's much better but you can try it out. 

for AMD it's whisper-blas-bin-x64.zip

**Comment by erturkdotgg** [comment]
> that's right, but if you really need v3 you could replace main.exe etc with [whisper.cpp](https://github.com/ggerganov/whisper.cpp/releases) version, idk if it's much better but you can try it out.
> 
> for AMD it's whisper-blas-bin-x64.zip

It didnt work. It says finished in 10 seconds. But no output.

**Comment by erturkdotgg** [comment]
> that's right, but if you really need v3 you could replace main.exe etc with [whisper.cpp](https://github.com/ggerganov/whisper.cpp/releases) version, idk if it's much better but you can try it out.
> 
> for AMD it's whisper-blas-bin-x64.zip

I did it but same thing happened :/ Is it possible for you to build a new version for v3 support?

**Comment by tigros** [comment]
i don't have AMD or Intel card to test with, so I'm in no rush to switch whisper versions. 

maybe try from cmd prompt to see if there's error message.

something like main.exe --language en --output-srt  --max-context 0 --model "P:\Models\ggml-base.bin" "P:\whisperwavs\test.wav"

replace model and wav paths. just be sure to cd to whisperer folder.

**Comment by erturkdotgg** [comment]
> i don't have AMD or Intel card to test with, so I'm in no rush to switch whisper versions.
> 
> maybe try from cmd prompt to see if there's error message.
> 
> something like main.exe --language en --output-srt --max-context 0 --model "P:\Models\ggml-base.bin" "P:\whisperwavs\test.wav"
> 
> replace model and wav paths. just be sure to cd to whisperer folder.

It worked. But it used my CPU and interesting thing is, accuracy has become very bad. The result was very good with Whisperer + large-v2. But when I did the same file with this command, the result was very bad.

**Comment by tigros** [comment]
gonna close this then, whisperer is all about GPU and checking VRAM etc, and no cards to test with..

**Comment by erturkdotgg** [comment]
> gonna close this then, whisperer is all about GPU and checking VRAM etc, and no cards to test with..

Soo, will there never be v3 support?

**Comment by tigros** [comment]
maybe in some months, not today!
