### ISSUE TITLE
"Virus detected" (2023-12-27)

### ISSUE THREAD

**Issue by DJuego** [tigros/Whisperer#41]
Sorry, but I feel I must inform you. 

In the last few days there have been several releases of Whisperer version 3.0. In the last one (2023-12-27) Windows Defender declares the download to be contaminated by a Trojan (Trojan:Win32/Wacatac.B!ml).  According to Window Defender, it is a "severe" threat.... :-O

DJuego

**Comment by tigros** [comment]
which file? just curious.

i won't be doing anything to fix that, so just mark the folder as safe. all the source is available and i don't suffer stupid antiviruses gladly.

**Comment by DJuego** [comment]
Thank you for your fast reply!

The problem was in the whisperer.exe. 

Well, I just tried to download it again... to investigate more about this issue. I just tried to download it again (2023-12-28) to investigate more about this issue... and it didn't complain! And I tried several times yesterday with the same result. I am puzzled.  (??)

Issue closed!

DJuego
