### ISSUE TITLE
Would you be against implementing MKV Language flags?

### ISSUE THREAD

**Issue by snintendog** [tigros/Whisperer#42]
Many MKVs have audio tracks with language flags set so when the program takes in the file could it not also set the language from this flag with a possibility to manually override this per video in batch if not set correctly or comes UND flagged?.. Also a secondary is take all audio tracks of an MKV and add them to the batch if that is possible.

This program already does wonders for me when I add stuff to its watch folder before I sort them in my jellyfin server.

**Comment by tigros** [comment]
That's a whole lot of work and very niche. There's also the problem of checking if the subs already exist, going to get convoluted.

You could use ffmpeg to extract the audio yourself, see https://superuser.com/questions/639402/convert-specific-video-and-audio-track-only-with-ffmpeg
https://askubuntu.com/questions/1139812/how-to-extract-specific-audio-track-track-2-from-mp4-file-using-ffmpeg

**Comment by snintendog** [comment]
That's fine just wanted to Stream line the process further. The Extraction method is what i already do for the Multi track vids. MKVToolnix and gMKVExtract GUI are the tools i use MKVMuxing Batch GUI too. MakeMKV made me really reliant on MKVs as a container ripping them from source easily.
