### ISSUE TITLE
Cantonese is missing

### ISSUE THREAD

**Issue by Snuupy** [tigros/Whisperer#43]
Hi,

[large v3 added a new language, Cantonese](https://github.com/openai/whisper/discussions/1762)

You can also verify the language list here, there are now 100 supported languages. https://github.com/openai/whisper/blob/main/whisper/tokenizer.py

Could you please add the language to the dropdown? Tokenizer should be `yue`.

**Comment by tigros** [comment]
there won't be v3 support for a while, unless Const-Me manages to support it.
