### ISSUE TITLE
Sometimes the app hangs and does nothing

### ISSUE THREAD

**Issue by tjesp** [tigros/Whisperer#48]
Sometimes when I have a long queue it just hangs on the last file for hours without ending the processing.

I had an example today where it was stuck on the last file for hours. It was a 22MB MP4 file so it should only take max 10-15 minutes.

The app have not crashed I can still cancel the processing.

I know this is not much to go on so how can I generate a proper error report for you next time it happens?

**Comment by tigros** [comment]
Hi,

looking at the code it can only happen if there's a ffmpeg.exe or main.exe process running AFAIK.

maybe check taskmgr look for those 2, maybe 1 got stuck?

**Comment by tjesp** [comment]
Yes main.exe was running. After I quitted it the processing ended.

**Comment by tigros** [comment]
ok i guess it had trouble with a certain file, do you know which one? might have to avoid those kinds.

**Comment by erturkdotgg** [comment]
Happens if you use large-v3
