### ISSUE TITLE
unsuccessful use

### ISSUE THREAD

**Issue by standyyyy** [tigros/Whisperer#5]
Hello, I have a question, I have not successfully used it on windows, it did not report an error, I first clicked "pick files" and then selected the model file, then dragged the audio file in, and then clicked "go" , and then only a wav audio file was generated for me, and then there was no translation. I don't see where is the result after recognition

**Comment by tigros** [comment]
If all the inputs are correct, sounds like you don't have a GPU? Is this on a laptop or something?

**Comment by standyyyy** [comment]
Hi，I'm glad you can reply me so quickly
I'm not sure if my operation is correct, but the steps are as I said above, my GPU is RTX 2080, and cuda was successfully installed (because I used it to run faster-whisper), so I'm sure it is working. I am running this project on a desktop computer, not a laptop

**Comment by tigros** [comment]
"pick files" is not for model, maybe send a screen shot right before clicking Go, Put the full path of the model where it says Model path, is Output dir set ok?
