### ISSUE TITLE
insufficient graphic memory

### ISSUE THREAD

**Issue by dat203lob** [tigros/Whisperer#51]
It prompts that insufficient graphic memory when run whisperer.exe and click GO. Could you please help me fix this ?
I have Nvidia GT 1030 with 2Gb Ram. Thanks! 
![Screenshot 2024-02-27 132930](https://github.com/tigros/Whisperer/assets/161409860/c1ff6ce1-acb9-498f-a0d5-6c5e53155c18)

**Comment by tigros** [comment]
Hi,

Are you using large or medium model? 2 GB isn't enough for those.

go to https://huggingface.co/getwavery/ggml-models/tree/main and try one of these instead.

ggml-base-en.bin
ggml-base.bin
ggml-small-en.bin
ggml-small.bin

**Comment by dat203lob** [comment]
> Hi,
> 
> Are you using large or medium model? 2 GB isn't enough for those.
> 
> go to https://huggingface.co/getwavery/ggml-models/tree/main and try one of these instead.
> 
> ggml-base-en.bin ggml-base.bin ggml-small-en.bin ggml-small.bin

It fixed. Thank you!

**Comment by mgfx** [comment]
What was the fix?

**Comment by ToiYeuTien** [comment]
> Hi,
> 
> Are you using large or medium model? 2 GB isn't enough for those.
> 
> go to https://huggingface.co/getwavery/ggml-models/tree/main and try one of these instead.
> 
> ggml-base-en.bin ggml-base.bin ggml-small-en.bin ggml-small.bin

Hi !
I'm using RTX 3060 12GB, ggml-large-v2.bin, ggml-large.bin, and I'm encountering a similar issue to the topic owner. Previously, I've been using your software normally, but today when I tried to use it, the software seems not to be working. When I upgraded to your latest version, it reported an error of insufficient graphic memory.

**Comment by tigros** [comment]
Hi,

what happens when you run GPUmembyproc.exe from cmd prompt? 

Also ggml-large.bin might be v3, only use v2.

thanks

**Comment by ToiYeuTien** [comment]
> Hi,
> 
> what happens when you run GPUmembyproc.exe from cmd prompt?
> 
> Also ggml-large.bin might be v3, only use v2.
> 
> thanks

Hi !
This is the message when i run with version 3.1

D:\Stable\Sound_to_Text\Whisper-Const-me\Whisperer>GPUmembyproc.exe
explorer.exe  7592  177,295,360  32,022,528
SearchHost.exe  9548  20,938,752  24,576
StartMenuExperienceHost.exe  9584  11,616,256  24,576
msedgewebview2.exe  10844  26,370,048  28,884,992
PhoneExperienceHost.exe  12440  10,424,320  24,576
NVIDIA Share.exe  12656  46,026,752  24,576
TextInputHost.exe  10452  21,164,032  24,576
OneDrive.exe  14256  10,055,680  24,576
Zalo.exe  13460  95,997,952  9,531,392
ShellExperienceHost.exe  15800  11,542,528  24,576
ZaviMeet.exe  13504  22,446,080  24,576
ZaloCall.exe  10528  22,446,080  24,576
Teams.exe  16640  19,861,504  24,576
msedgewebview2.exe  16548  11,915,264  24,576
BlueStacksServices.exe  19412  10,780,672  24,576
msedge.exe  19880  11,636,736  24,576
msedgewebview2.exe  12308  55,050,240  24,576
SystemSettings.exe  8180  10,854,400  24,576
main.exe  13456  4,673,556,480  710,430,720
WindowsTerminal.exe  18088  35,069,952  30,527,488
python.exe  5208  19,224,592,384  11,188,215,808
Total GPU memory:  3,221,225,472


I tried again with version 3.0 and it worked (got full 12gb vram)

D:\Stable\Sound_to_Text\Whisper-Const-me\test>GPUmembyproc.exe
explorer.exe  7592  178,307,072  37,195,776
SearchHost.exe  9548  20,938,752  24,576
StartMenuExperienceHost.exe  9584  11,616,256  24,576
msedgewebview2.exe  10844  26,370,048  28,950,528
PhoneExperienceHost.exe  12440  10,424,320  24,576
NVIDIA Share.exe  12656  46,026,752  24,576
TextInputHost.exe  10452  21,164,032  24,576
OneDrive.exe  14256  10,055,680  24,576
Zalo.exe  13460  95,952,896  9,486,336
ShellExperienceHost.exe  15800  11,542,528  24,576
ZaviMeet.exe  13504  22,446,080  24,576
ZaloCall.exe  10528  22,446,080  24,576
Teams.exe  16640  19,861,504  24,576
msedgewebview2.exe  16548  11,915,264  24,576
BlueStacksServices.exe  19412  10,780,672  24,576
msedge.exe  19880  11,636,736  24,576
msedgewebview2.exe  12308  55,050,240  24,576
SystemSettings.exe  8180  10,854,400  24,576
main.exe  13456  4,673,519,616  664,305,664
WindowsTerminal.exe  18088  47,173,632  45,907,968
python.exe  5208  19,224,592,384  11,188,215,808
Total GPU memory:  12,718,178,304

Can you help me check again, thank you!

**Comment by tigros** [comment]
Ah it must be related to [#53](https://github.com/tigros/Whisperer/issues/53)

please try attached GPUmembyproc in cmd prompt to see if i can fix it, otherwise might have to remove #53 Radeon mod.

what model laptop is this? 

[GPUmembyproc.zip](https://github.com/tigros/Whisperer/files/14476289/GPUmembyproc.zip)

**Comment by tigros** [comment]
i'll presume it was a version mixup. if not feel free to reopen.

**Comment by tigros** [comment]
turns out it was my fault, the compilation was set to Any CPU, needed to be x64 for GPUmembyproc, so i'm the one who was mixed up! sorry about that! Replaced version 3.1 just now.

**Comment by ToiYeuTien** [comment]
> turns out it was my fault, the compilation was set to Any CPU, needed to be x64 for GPUmembyproc, so i'm the one who was mixed up! sorry about that! Replaced version 3.1 just now.

Thank you very much !
