### ISSUE TITLE
insufficient graphic memory / GPUmembyproc.exe returns 0

### ISSUE THREAD

**Issue by mgfx** [tigros/Whisperer#53]
Radeon RX 470 8 GB
DirectX 12
Running GPUmembyproc shows:

`GPUmembyproc.exe
Total GPU memory:  0
`

**Comment by mgfx** [comment]
My card name doesn't start with AMD.... opened PR https://github.com/tigros/Whisperer/pull/54

**Comment by tigros** [comment]
merged, thank you.
