### ISSUE TITLE
translation question

### ISSUE THREAD

**Issue by shiwangyan** [tigros/Whisperer#56]
Hi

I primarily use Whisperer for transcribe both Chinese and English videos, and setting its language to Chinese.

Today, I noticed that after transcribing English videos, they were automatically translated into Chinese. 

How should I configure the software to only perform transcription without translation?

**Comment by tigros** [comment]
Hi,

for English videos just set the language to English not Chinese.

you'll have to run each language separately.

it's interesting it can translate to any language, some might find it useful. idk about the quality.
