### ISSUE TITLE
hope relax graphics memory size limit

### ISSUE THREAD

**Issue by lforlgg** [tigros/Whisperer#57]
Dear tigros,many thks you for you share your good work!love!

My Nvidia graphics card is 1050 Ti with **4G** graphics memory.
when I load ggml-large.bin model,Const-me Whisper WhisperDesktop can run well.
but,Whisperer 3.1 alert:Insufficient graphics memory for this model!

![whisper-tigros-4G](https://github.com/tigros/Whisperer/assets/105794681/da7dcc40-d17e-420d-8f0f-9cc20e9c4f80)
![whisper-tigros-ok](https://github.com/tigros/Whisperer/assets/105794681/18979be4-12ed-4223-9395-4159bc3613a0)

**Comment by tigros** [comment]
Hi,

try this one, changed from 4.3 GB to 3 GB.

[whisperer.zip](https://github.com/tigros/Whisperer/files/14568715/whisperer.zip)

**Comment by lforlgg** [comment]
> Hi,
> 
> try this one, changed from 4.3 GB to 3 GB.
> 
> [whisperer.zip](https://github.com/tigros/Whisperer/files/14568715/whisperer.zip)

That's great!This version working fine.✌❤

**Comment by lforlgg** [comment]
[ico for tigros whisper.zip](https://github.com/tigros/Whisperer/files/14569791/ico.for.tigros.whisper.zip)
an icon for whisperer, hope you like it!☺

**Comment by tigros** [comment]
hmm thanks but not quite, welcome to send more if you like. maybe just the swirly from openai? or some other existing..

**Comment by lforlgg** [comment]
> hmm thanks but not quite, welcome to send more if you like. maybe just the swirly from openai? or some other existing..
The icon mentioned above was downloaded from the internet and is not for commercial use.
This post was created by me and has no copyright. Please use it freely.

[voice_to_txt.zip](https://github.com/tigros/Whisperer/files/14572204/voice_to_txt.zip)

**Comment by tigros** [comment]
ok replaced v3.1 with new icon, thanks!

i'm open to future changes if you or anyone has better ideas.

Cheers!

**Comment by tigros** [comment]
ha! almost forgot, here's one for your 4 GB card.

[whisperer.zip](https://github.com/tigros/Whisperer/files/14579198/whisperer.zip)

**Comment by lforlgg** [comment]
Considering that many people are not fully prepared for the arrival of the AI era, the graphics card configuration is relatively low.

The next version,maybe consider providing an option for users, free to adjust their graphics card capacity limit. 

Just simultaneously indicating : "graphics card memory below 4GB may cause slow or unpredictable errors."
Provide a status bar:

Thank you very much for your special attention.
Enjoying your special version❤

**Comment by tigros** [comment]
come to think of it i could just check the total memory and adjust the large model requirements, so no risk of causing problems with cards that have more memory, running too many instances at a time.

i did notice the display issues, looks like a DPI problem, to test set your DPI to 125%, or it could be some system font difference.
i'm guessing your DPI is 100% right? if you don't how to set DPI just type DPI in the taskbar. might be a good idea to reboot.

**Comment by lforlgg** [comment]
Yes, my display settings are 100% of the display layout. There is no zooming in and out.
Dell 24" monitor.
The resolution is: 1920*1200
System is: Win10 2019 Ltsc x64

Those interface flaws are probably related to my system's default fonts.
My thought is whether it might be better to make the window's text and controls less tightly arranged, leaving some space for compatibility.
But it's just some minor issues that bother you a lot...

**Comment by tigros** [comment]
so i tested 100% DPI in win 10 and it was ok, so i dunno what font you got there, personally i've never even come across anyone changing system font.

changed the icon again, to give credit to openai plus i like it better. put new 3.1 just now.

also fixed for 4GB cards + large model.

**Comment by lforlgg** [comment]
v3.1 New version works well!😄

By specifying the interface font , there will be no unpredictable misalignments.

about the font:
Possibility to specify the interface as a specific font, also avoiding unpredictable misalignments.
such as Const-me Whisper using "Calibri" is fine.

There are some obvious flaws in your new replacement icon.
![icon_notFine_ziped](https://github.com/tigros/Whisperer/assets/105794681/01af6bd9-52e0-4738-9de9-277d07af8db3)

I also really like openAI😄

Attached are several similar icon materials, you may want to see if there is a beautiful and like the material.



[openai icons.7z.zip](https://github.com/tigros/Whisperer/files/14596199/openai.icons.7z.zip)

**Comment by tigros** [comment]
ok that icon not bad.

changed font, new 3.1 online.

**Comment by lforlgg** [comment]
new 3.1-14th March.
I've run it and the interface is comfortable now.
It's functioning normally.
![v31_ziped](https://github.com/tigros/Whisperer/assets/105794681/19f4f92f-bd3d-4acf-81a7-537bd15f7264)

It looks pretty much perfect already. 🥰
tks!

**Comment by tigros** [comment]
see 3.4 for context menu.
