### ISSUE TITLE
Add support for transcribing videos from youtube

### ISSUE THREAD

**Issue by Koaxz** [tigros/Whisperer#58]

**Comment by tigros** [comment]
what's the problem with youtube videos? unless you mean direct from youtube, nope, figure out how to download the videos then there shouldn't be any problem.

**Comment by tjesp** [comment]
Use yt-dlp first.

https://github.com/yt-dlp/yt-dlp

**Comment by tigros** [comment]
or check out [FreeTube](https://github.com/FreeTubeApp/FreeTube)

click the download button (arrow pointing down) and you'll see at the bottom of the list you can get the auto generated subtitles.

they're in a strange format though, you can use this [Subtitle Converter](https://gotranscript.com/subtitle-converter) I point you there because many others won't work with that format.

so now you don't need whisper :) save electricity..

**Comment by ToiYeuTien** [comment]
> hoặc xem [FreeTube](https://github.com/FreeTubeApp/FreeTube)
> 
> nhấp vào nút tải xuống (mũi tên chỉ xuống) và bạn sẽ thấy ở cuối danh sách bạn có thể nhận được phụ đề được tạo tự động.
> 
> Tuy nhiên, chúng có định dạng lạ, bạn có thể sử dụng [Trình chuyển đổi phụ đề](https://gotranscript.com/subtitle-converter) này . Tôi chỉ cho bạn ở đó vì nhiều định dạng khác không hoạt động với định dạng đó.
> 
> nên bây giờ bạn không cần thì thầm :) tiết kiệm điện..



> or check out [FreeTube](https://github.com/FreeTubeApp/FreeTube)
> 
> click the download button (arrow pointing down) and you'll see at the bottom of the list you can get the auto generated subtitles.
> 
> they're in a strange format though, you can use this [Subtitle Converter](https://gotranscript.com/subtitle-converter) I point you there because many others won't work with that format.
> 
> so now you don't need whisper :) save electricity..

Hi !
The issue I'm experiencing is unrelated to this topic. I'm using your software, Whisperer. I'm having a problem with the software automatically starting (it starts when my computer is in use, not at Windows startup). The issue started from version 3.1, and even after uninstalling and reinstalling version 3.2, it still automatically starts when my computer is in use. Could you please check into this?
Thank you so much for this useful software.

**Comment by tigros** [comment]
Hi,

you must have a scheduled task, click the Watch Schedule button then Cancel to delete it.

**Comment by ToiYeuTien** [comment]
> Hi,
> 
> you must have a scheduled task, click the Watch Schedule button then Cancel to delete it.

oh thank you !
