### ISSUE TITLE
Want to support batch transcription for multiple folders

### ISSUE THREAD

**Issue by SaraKale** [tigros/Whisperer#59]
Hi, this tool is great to use!  I like it very much! :grinning:
I wonder if it can support multiple folder traversal transcription?  I have a lot of folders, if it is a single file dragged into it can be transcribed, but multiple folders are too much, want the function of batch conversion folders! :sob:
Thank you very much!
![Snipaste_2024-03-16_21-15-19](https://github.com/tigros/Whisperer/assets/42092947/213dd8dc-ae02-4b02-8168-c559a739d22d)

**Comment by tigros** [comment]
you could find an app that displays all the files then drag and drop into Whisperer. Many apps can do that, file finders, Directory Opus or one i wrote mysys @ integritech.ca. Should be able using Windows search but need to configure it a little i think, like tell it what folders to index etc. So basically you want to use drag and drop.

**Comment by SaraKale** [comment]
Wow!  That's a good idea! I can search for file suffix.wav in the current folder and then drag and drop! Thank you very much!!
