### ISSUE TITLE
audio file issue 

### ISSUE THREAD

**Issue by godv23** [tigros/Whisperer#6]
Fantastic job,  it's a very useful tool. :blush:
In version 2.5, When I tried to extract subtitles from an **audio file**, it still attempted to extract audio from the file.  This issue was not present in version 2.3.
I don't really understand programming, wouldn't this be more time-consuming?

![2023-04-28_221457](https://user-images.githubusercontent.com/71914458/235173783-79591de3-70fa-4cd8-a00f-51940be7cd46.png)

**Comment by tigros** [comment]
yes everything goes through ffmpeg even wav files, it increases volume too so that could be useful for accuracy sometimes. The .wav.wav file should be deleted automatically when done. It's not very time consuming wouldn't worry about it.
