### ISSUE TITLE
love,hope further : estimate how long this task and give a text hint in the title bar when completed,and easy locate the files

### ISSUE THREAD

**Issue by lforlgg** [tigros/Whisperer#62]
Dear tigros,

After using it for a period of time I love this gadget so much.🤩
Could you make it go further:

✅1. estimate how long this task will take,based on the recorded completion of the last time,and give a hint in the title bar.
✅2. give a text hint :"All completed." in the title bar,when all tasks have been completed.
✅3. when files in the task list,right-click on a audio,show menu:locate it in file manager.
✅4. when files in the task list,double click a audio,open it with an audio player.

Many Thanks! 😍

**Comment by tigros** [comment]
i'm working on #1 now, sure is convoluted but feasible, kinda fun too :)

**Comment by tigros** [comment]
Please try 3.3 at your earliest convenience.
The time remaining won't be very accurate but better than nothing.
Also double click items to open in default player.

**Comment by lforlgg** [comment]
many tks.
I have tested v3.3.
✅double click items to open in default player.
❓The time remaining，the function doesn't seem to work, it keeps showing 00:00:00
❤about right-click to show menu:locate it in file manager.pls see the attached code snippet to see if it works!😁

[whisperer_SHOpenFolderAndSelectItemsHelper.zip](https://github.com/tigros/Whisperer/files/14809303/whisperer_SHOpenFolderAndSelectItemsHelper.zip)

**Comment by lforlgg** [comment]
many tks.
I have tested v3.3.
✅double click items to open in default player.
❓The time remaining，the function doesn't seem to work, it keeps showing 00:00:00
❤about right-click to show menu:locate it in file manager.pls see the attached code snippet to see if it works!😁

[whisperer_SHOpenFolderAndSelectItemsHelper.zip](https://github.com/tigros/Whisperer/files/14809303/whisperer_SHOpenFolderAndSelectItemsHelper.zip)

**Comment by tigros** [comment]
are you selecting a bunch of files or just 1? i wonder also if there are non-english ffmpeg? yours is english right? i didn't find any with google search but who knows. it's looking for "Duration:" in ffmpeg output.

**Comment by lforlgg** [comment]
✅The time remaining the function--OK!

About audio decoder:
Yes, originally I copied ff from the decoder package that comes w
ith a Chinese classic and efficient MP4 compression tool (maruko.appinn.me) (the file size is relatively small). But I also used the latest version on github, and this doesn't affect the time estimation issue.

About the remaining time show
I see what you mean now, and it turns out that your logic is that when processing multiple files, the time remaining in the queue processing is extrapolated based on the percentage of time the first file in the list completes.
It's not what I originally thought:whisperer remembered the processing efficiency of the last run, and used it to extrapolate the time used for the current task (whether task is a single file or multiple files).

How about this: 
instead of displaying remaining  00:00:00 (Easily misinterpreted as functionally broken) 
display remaining --:--:--（when the estimate is not yet available）

**Comment by lforlgg** [comment]
✅The time remaining the function--OK!

About audio decoder:
Yes, originally I copied ff from the decoder package that comes w
ith a Chinese classic and efficient MP4 compression tool (maruko.appinn.me) (the file size is relatively small). But I also used the latest version on github, and this doesn't affect the time estimation issue.

About the remaining time show
I see what you mean now, and it turns out that your logic is that when processing multiple files, the time remaining in the queue processing is extrapolated based on the percentage of time the first file in the list completes.
It's not what I originally thought:whisperer remembered the processing efficiency of the last run, and used it to extrapolate the time used for the current task (whether task is a single file or multiple files).

How about this: 
instead of displaying remaining  00:00:00 (Easily misinterpreted as functionally broken) 
display remaining --:--:--（when the estimate is not yet available）

**Comment by tigros** [comment]
the ffmpeg that comes with MarukoToolbox is from 2016 but it is English and should be fine.

updated 3.3 just now with your --:--:-- suggestion, good idea!

about the right click menu, i can do that, but in no rush, maybe in 3.4. So what to do when multiple files are selected then right click? 2 options, act on all the selected files, or act only on the one where the mouse is.

**Comment by lforlgg** [comment]
about the right click menu:
act only on the one where the mouse focus on.😁surely!

**Comment by lforlgg** [comment]
❤"pick files" button:
Remembers the last completed file, in the folder where it is located, regardless of whether the file list is cleared.
so that the next time a new task is added, from the same folder.

**Comment by tigros** [comment]
it remembers the last folder you picked files from tho right? that's how it should be, built into windows actually.

**Comment by lforlgg** [comment]
> it remembers the last folder you picked files from tho right? that's how it should be, built into windows actually.

If the file was added by drag-and-drop, it seems that the button doesn't remember the location of the last file.

**Comment by tigros** [comment]
Added right click context menu in 3.4, missing anything?

**Comment by lforlgg** [comment]
@tigros 
It's awesome. It's even better than I thought it would be.🤩👍

**Comment by tigros** [comment]
ok thanks! guess can close this out, feel free to reopen if anything.
