### ISSUE TITLE
Older CPUs (non-AVX) support.

### ISSUE THREAD

**Issue by Uka-Uka** [tigros/Whisperer#63]
Hi, @tigros! Would you please distribute a whisperer version based on const-me whisper SSE-ONLY branch?

**Comment by tigros** [comment]
Hi,

You can replace main.exe and related files yourself, i'm sticking with const-me version, probably for a pretty long time from the looks of it.

**Comment by Uka-Uka** [comment]
Thanks for replying @tigros! I hope I didn't misunderstand you. Whisper SSE-ONLY is still "const-me version" just another branch without AVX. I meant this one: https://github.com/Const-me/Whisper/tree/SSE-Only

It would be perfect if your time allow to build from this branch and release an SSE-compatible whisperer version along side with AVX version as usual. anyway I really appreciate your work.

**Comment by tigros** [comment]
but i didn't even compile it, i just took from const-me releases, cli.zip to be exact. too bad he doesn't have a non avx in there to make it simple.
