### ISSUE TITLE
Can you add support for multispeaker(different speaker ID labels)

### ISSUE THREAD

**Issue by lforlgg** [tigros/Whisperer#64]
hi tigros,
😊
Can you add support for Multispeaker(different speaker ID labels)

refer：
https://github.com/m-bain/whisperX
https://github.com/pyannote/pyannote-audio

**Comment by tigros** [comment]
Hi,

No, that wouldn't happen here, you'd have to ask someone else like const-me or ggerganov, and this project shouldn't be using python, needs to be C# or C++.
