### ISSUE TITLE
Regarding the error reported when using version 3.4

### ISSUE THREAD

**Issue by ssswww0004** [tigros/Whisperer#65]
Hello, first of all, thank you very much for making such an easy-to-use software. However, after updating to version 3.4, I found a usage problem. During the process of translating video speech, the following error interface and error content will pop up. If you do not click to exit after reporting an error, the translation can still be completed. If you click to exit, you will exit the software directly. For the same original video, no error occurred when I tried using version 3.2. Please tell me how to solve this problem, thank you!

![202405021155](https://github.com/tigros/Whisperer/assets/25629849/659337d9-0694-4296-99f9-004b37b39d79)

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.FormatException: 输入字符串的格式不正确。
   在 System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   在 System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   在 whisperer.Form1.timer1_Tick(Object sender, EventArgs e)
   在 System.Windows.Forms.Timer.OnTick(EventArgs e)
   在 System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.9232.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
whisperer
    程序集版本:3.4.0.0
    Win32 版本:3.4.0.0
    基本代码:file:///D:/Desktop/Whisperer/whisperer.exe
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.9236.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.9236.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.9181.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ObjectListView
    程序集版本:2.9.1.1072
    Win32 版本:2.9.1.0
    基本代码:file:///D:/Desktop/Whisperer/ObjectListView.DLL
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by tigros** [comment]
Hi,

Interesting! From a cmd prompt could you paste the output of ffmpeg -i "thevideo.mp4"

where thevideo.mp4 is full path to problem vid.

Thanks

**Comment by ssswww0004** [comment]
Hello, thank you very much for your reply. Do you mean that there is a problematic video in my video, so the error is reported? But I usually translate a lot of videos in batches, so I don’t know which video has the problem, and I re-translated the same video using version 3.2 without any errors. Thanks!

**Comment by tigros** [comment]
I just want to make sure there isn't some language issue with ffmpeg, check the output and look for "Duration:", anything odd there since you are on a Chinese system? You don't need to paste the whole output actually, just the line where "Duration:" is.

this is something new in 3.4, trying to estimate the time remaining.

**Comment by ssswww0004** [comment]
Hello, I changed a batch of video file translations and unchecked the "Skip if exists" option, but the same error still occurred. However, as long as you don't click to exit, you can continue to use it and the translation can still be completed. If it doesn't work, just Use it this way. Thank you for your efforts.

**Comment by tigros** [comment]
what are the values of Elapsed and Remaining on the screen when this happens? The error happens when interpreting whatever is next to Remaining, which should be --:--:-- at first then once it completes the first file changes to something like 00:15:30. Also make sure the whisperer.exe date is 4/7/2024. Thanks for taking the time, look forward to your reply!

**Comment by ssswww0004** [comment]
Hello, when an error occurs, the values of Elapsed and Remaining are as shown in the figure. The value of Elapsed will still proceed correctly until all tasks are completed. The value of Elapsed will not cause errors, but the value of Remaining will remain at the wrong value for a long time ( The error value is random) and does not change. In a certain period of time, maybe the last few tasks, the countdown will resume, and then return to zero until the end of the task. It is useless to click Continue while the task is in progress. The error box will always pop up and If it exists, the entire software will be closed directly when you click Exit. However, after all tasks are completed, the error box will not appear again when you click Continue. The Whisper.exe date is 4/7/2024.

![202405021155](https://github.com/tigros/Whisperer/assets/25629849/ebe5939f-d140-4ed4-8b06-864731a5b084)
