### ISSUE TITLE
Openai whisper small model

### ISSUE THREAD

**Issue by tjesp** [tigros/Whisperer#66]
I had the chance to try the original Openai Whisper on my linux system. I cannot use the large model since my graphics card is 8GB.

However I found that generally the small model in Openai whisper were as accurate as the large model in whisperer.

I thought it was supposed to just be a faster implementation than openai whisper but it seems that some things might be lost in the translation.

Do you have any comments on that could it be improved any way?

**Comment by tigros** [comment]
Hi,

if i recall original Openai Whisper is CPU only, so why you need graphics memory? it's python right? maybe you mean RAM.

ya i use base myself even smaller than small, works fine. maybe large can handle subtle speech a bit better.

**Comment by tjesp** [comment]
No Openai Whisper is python but it can use graphics card acceleration via pytorch. Thanks I am closing this now.
