### ISSUE TITLE
系统找不到指定的文件

### ISSUE THREAD

**Issue by zpofrp** [tigros/Whisperer#68]
我在使用的时候，提示：系统找不到指定的文件，请问我是哪里设置错了，这个程序有使用说明文档没
![Snipaste_2024-05-27_13-42-45](https://github.com/tigros/Whisperer/assets/38334945/6a296fe7-cc6d-418b-8217-fdad78ecb116)
[
![Snipaste_2024-05-27_13-43-02](https://github.com/tigros/Whisperer/assets/38334945/130e45ff-3560-4165-9aed-7686de24dc10)
](url)

**Comment by zpofrp** [comment]
I konw， I dont set ffmpeg path.

**Comment by tigros** [comment]
i'll make that message clearer next version.
