### ISSUE TITLE
no srt generated。生成wav文件之后就没有反应了

### ISSUE THREAD

**Issue by ilovebody** [tigros/Whisperer#7]
后续cpu gpu都没有调用，也没任何提示，字幕等一天也不出来

**Comment by tigros** [comment]
did you set the model path properly? what GPU you have?

**Comment by kencsie** [comment]
I have same problem like ilovebody, my gpu is rtx 3060.
Do I need to preinstall something else?

model path is like below
‪C:\Users\U\Desktop\Whisperer\ggml-medium.bin

**Comment by tigros** [comment]
please try v2.6 it will tell you if something is missing. 

also try base model if that doesn't help.

Thanks.

**Comment by luceln** [comment]
试试2.2版本，好像之后的版本都有这个问题

**Comment by tigros** [comment]
what does "reg query hklm\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000 /v HardwareInformation.qwMemorySize" return?

**Comment by kencsie** [comment]
> what does "reg query hklm\SYSTEM\ControlSet001\Control\Class{4d36e968-e325-11ce-bfc1-08002be10318}\0000 /v HardwareInformation.qwMemorySize" return?

it returns error message, says that system can't find that register.

btw, version 2.2 works.

**Comment by tigros** [comment]
sorry didn't notice, please try again but put a backslash after the word Class, i think github parsed it out..
