### ISSUE TITLE
請問是否有使用的說明書

### ISSUE THREAD

**Issue by Jackchen1005** [tigros/Whisperer#70]
從WhisperDesktop看到大大的留言跑來這裡的，
看起來Whisperer可以做到WhisperDesktop做不到的可指定非純英文路徑及批次處理字幕
只是不知道您的程式是否有使用說明，似乎沒看到執行的時候有即時的轉錄結果？
如果有程式說明，再麻煩讓我參考喔，感謝！！

**Comment by tigros** [comment]
no there's no real time display, the output goes to files, in the output folder you specify.

nope no documentation, but feel free to ask if something's not clear.
