### ISSUE TITLE
转出的文字呈现繁体字，官方仓库转出来是简体字。

### ISSUE THREAD

**Issue by leungMr** [tigros/Whisperer#71]
同样一个视频文件，转出来的文字有简体、有繁体，且没有规律性。
而官方仓库转出结果没出现这种问题。

**Comment by tigros** [comment]
hi,

you can try using the Initial prompt, paste a phrase of simplified Chinese in the text box that might help. keep trying different phrases if it doesn't work, otherwise not much i can do.

**Comment by leungMr** [comment]
Thank you for your prompt reply. I will test your suggestions in my free time. Once I confirm its validity, I will reply here
