### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by netaat2088** [tigros/Whisperer#72]
Hello, Whisperer is very useful, but there are some bugs and suggestions:
1. When dragging a folder to import, the files in the folder cannot be read for processing. You need to search for the files separately and drag them into the software for processing to work properly.
2. Maybe because the recognition library is not perfect, some professional terms will not translate well when they are recognized, but there is a certain regularity. Can a replacement function of the comparison table be added? For example, Maui in c# will be forced to be converted to "毛伊岛" when it is recognized. If there is a dictionary that will convert it into subtitles, the entire subtitle file will be replaced regularly. This will make the translation result more perfect. This dictionary file can be customized, and multiple replacement objects can be set.
For example:(Wrong translation results and desired replacement text)
"毛伊岛": "Maui"
"尖锐者": "c#"
"点网": ".Net"
Thank you for your selfless dedication.
Because my English is not good, I used Google to translate what I want to express. I wonder if you can understand my expression?

**Comment by tigros** [comment]
Hi,

It's not too difficult to add folder support, but there are 2 options, recurse the folder or not? Maybe pressing shift key means recurse? probably just always recurse is ok.

#2 i guess you would need some post process on the .srt, it could be simple search and replace, or something more involved, up to you, but not in the scope of this project.

**Comment by tigros** [comment]
Can now drag/drop folders in v3.5.
