### ISSUE TITLE
Possibility to open a terminal window

### ISSUE THREAD

**Issue by HumanError13** [tigros/Whisperer#75]
More of a feature request or question here:

First off, this tool is genious, thanks a lot! What I really miss though is having the option to open a terminal window and see the progress. This is also possible with the Const-me version, which is the underlying engine of this project as well, as far as I understand. Sometimes there are issues like repeating words and I would like to see this happening in an early stage, so I can cancel the process. Can this be implemented?

Thanks and best regards

**Comment by tigros** [comment]
so what do you put in the console if 6-7 conversions running simultaneously? also as it is when you click cancel it doesn't kill the currently running processes, it just doesn't proceed with remaining files. the processes could be killed but it's not implemented as of now. it would be a bit messy too, kill all ffmpeg and const-me processes, also delete the partial output files if any.

**Comment by tigros** [comment]
they do have separate output but i was thinking one console screen not a bunch, or maybe left side with file names and you click those to see the output on right side. major pain coding wise and not generally useful enough for everyone.

if you have ideas go ahead, case by case determine feasibility/usefulness.

cheers!

**Comment by HumanError13** [comment]
> they do have separate output but i was thinking one console screen not a bunch, or maybe left side with file names and you click those to see the output on right side. major pain coding wise and not generally useful enough for everyone.

Understandable. Just had a second thought: The console screen could be made available if only one process is allowed at once. I can imagine this would be helpful in some cases for debugging. (Has not the highest priority for me personally, though)

**Comment by tigros** [comment]
gonna pass on this at least for now. maybe if popular demand :)
