### ISSUE TITLE
Picking different languages for different files in the batch

### ISSUE THREAD

**Issue by HumanError13** [tigros/Whisperer#77]
Hi tigros,

Another feature request. I regularly have to transcribe files with different languages (without translation) and I have to start for each language another batch. It would be really useful, if one could somehow define for each file on its own the language to be used. Some thoughts:

1. My first idea would be to have a dropdown menu in the file list to select a language, which can differ from the standard language picked below. 

2. The second idea is based on using a language code in the filename, e.g. `file1_en.mkv` and `file2_de.mkv`. Then Whisperer could detect by the filename suffix which language should be used instead of the predefined standard language.

3. A different solution would be to enable the automatic language prediction of the whisper model by not enforcing the language, but since this is not working in the const-me version, I assume you cannot enable it as well, right?

**Comment by tigros** [comment]
done in 3.6, please test it out!

**Comment by HumanError13** [comment]
Amazing! Works great. Thank you so much!
