### ISSUE TITLE
Changing the sound when done

### ISSUE THREAD

**Issue by HumanError13** [tigros/Whisperer#78]
Hi again,

I rely on the "When done: Play sound" feature, which is absolutely great when keeping it running in the backkground and doing other work. But more than enough I'm about to get a heart attack when suddenly my headphones are screaming "TADAAA". I don't know about C++ and how to compile stuff. 

I guess it's line 731 in Form1.cs to be changed:

```
            else if (comboBox2.Text == "Play sound")
                new SoundPlayer(Properties.Resources.tada).Play();
```

to something like:

```
            else if (comboBox2.Text == "Play sound")
                new SoundPlayer("custom.wav").Play();
```

So one could place any custom.wav file in the folder of the main.exe and it should play that, right? Just a suggestion, maybe there are better solutions.

**Comment by tigros** [comment]
can do that, make it load sound.wav which you can replace. super easy to do.

**Comment by HumanError13** [comment]
Awesome, thanks!! 

If you are going for standard windows sounds, I find Alarm03.wav or Ring06.wav in Windows 10 quite pleasing, for example. As found in the Windows/Media folder.

**Comment by tigros** [comment]
done in 3.6
