### ISSUE TITLE
为什么没生成srt字幕文件，生成了一个wav音频文件

### ISSUE THREAD

**Issue by kKevin0001** [tigros/Whisperer#79]
我是这么设置的，如图
最后没有srt文件出现，却出现了一个wav文件
![image](https://github.com/user-attachments/assets/ce19c471-8541-40ab-88be-7a952df388ca)

**Comment by tigros** [comment]
Hi,

In cmd prompt cd to whisperer folder and put main.exe --language zh --output-srt --max-context 0 --model path\to\model.bin path\to\wav.wav

likely some error there.

**Comment by kKevin0001** [comment]
> Hi,
> 
> In cmd prompt cd to whisperer folder and put main.exe --language zh --output-srt --max-context 0 --model path\to\model.bin path\to\wav.wav
> 
> likely some error there. maybe anitivrus deleted main.exe? also is that a plus sign in file name? that'll break things for sure.

现在又能生成自动srt文件了，之前只会生成wav文件，现在会先生成wav文件，然后生成srt文件，然后把wav文件自动删了

**Comment by tigros** [comment]
i don't know if you are using large model but maybe something was using GPU memory so it was waiting for enough memory to proceed. Did the Go button change from Cancel back to Go? If stuck on Cancel then it was waiting. You can see what is using GPU memory by running GPUmembyproc.exe from cmd prompt.

**Comment by kKevin0001** [comment]
> i don't know if you are using large model but maybe something was using GPU memory so it was waiting for enough memory to proceed. Did the Go button change from Cancel back to Go? If stuck on Cancel then it was waiting. You can see what is using GPU memory by running GPUmembyproc.exe from cmd prompt.

我记得在使用这个软件的时候，没有其它应用正在大量占用显存，那时显卡使用率应该在10%以下，而且按钮很快由Go编程Cancel了

提个小建议，假设真的是因为显存不足导致srt没有生成，那能不能显示哪个文件生成失败了，并且自动删除生成的wav文件呢？

**Comment by tigros** [comment]
it's hard to explain what happened there, most cases would have shown an error message, like missing or failed main.exe.

Be nice if can reproduce and maybe send the .wav or something.

I'll add that check you suggested in next version. It's also strange the .wav wasn't deleted, looking at the code it should have been if main.exe did execute. Could be strange file name with plus sign idk.

**Comment by kKevin0001** [comment]
> it's hard to explain what happened there, most cases would have shown an error message, like missing or failed main.exe.
> 
> Be nice if can reproduce and maybe send the .wav or something.
> 
> I'll add that check you suggested in next version. It's also strange the .wav wasn't deleted, looking at the code it should have been if main.exe did execute. Could be strange file name with plus sign idk.

目前来说一切正常了，等下次出现异常情况时我会继续向你反馈

**Comment by tigros** [comment]
did add check if generated output after main.exe exits in version 3.6
