### ISSUE TITLE
I tried V2.6 and there was no srt file except for the output wmv

### ISSUE THREAD

**Issue by Kanson4** [tigros/Whisperer#8]
I tried V2.6 and there was no srt file except for the output wmv

reg query hklm\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}
    Class    REG_SZ    Display
    ClassDesc    REG_SZ    @c_display.inf,%ClassDesc%;Display adapters
    IconPath    REG_MULTI_SZ    %SystemRoot%\system32\setupapi.dll,-1
    LowerLogoVersion    REG_SZ    6.0

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\Configuration
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\Properties

**Comment by tigros** [comment]
Hi,
what about reg query hklm\SYSTEM\ControlSet001\Control\Class\\{4d36e968-e325-11ce-bfc1-08002be10318}\0000 /v HardwareInformation.qwMemorySize

what gpu is it?

**Comment by Kanson4** [comment]
return:
HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000
    HardwareInformation.qwMemorySize    REG_QWORD    0x80000000

HD7850 2G RAM,I use small.bin model,
Using "WhisperDesktop" programs is fine.
thanks

**Comment by Kanson4** [comment]
Ok, maybe because it is slow and there is no progress bar, I can't know the status. I can only observe the GPU occupation to make sure it is working, thank you

**Comment by tigros** [comment]
ah ok if the Go button reads Cancel, it's working.
