### ISSUE TITLE
建议：增加进度条以显示处理进度

### ISSUE THREAD

**Issue by kKevin0001** [tigros/Whisperer#80]
目前有显示预计的剩余处理时间，但是它不太直观，希望可以增加进度条，进度条可以很直观的表现出来处理进度

**Comment by basicbh** [comment]
progress from main.exe,and main.exe not new version.

**Comment by kKevin0001** [comment]
> progress from main.exe,and main.exe not new version.

感谢你的软件开发工作，这个软件很好用

你是说进度来源于main.exe，程序没法预估总用时并用进度条显示出来吗？
main.exe不是最新版本是什么意思，升级到最新版有什么变化吗，在进度显示这部分？

**Comment by tigros** [comment]
ok done. replaced v3.6
