### ISSUE TITLE
Batch processing said i have no ffmpeg.exe

### ISSUE THREAD

**Issue by edmlover** [tigros/Whisperer#81]
I can do 1,2,3...10 video batch process, but when it reach higher such as 65 videos, it always say ffmpeg.exe not found, is this ffmpeg's issue??
Anyway thanks, the origin whisper can only transcribe one by one, your software save me lot of time.

**Comment by tigros** [comment]
ha that's a new one! what do you have in max at once? 10? how much RAM/VRAM? open task manager is RAM getting full?

what Windows version? try lowering max at once.

**Comment by kKevin0001** [comment]
我最高同时处理100个视频文件，没有出现你说的这个问题

> 我可以进行 1、2、3...10 个视频批处理，但是当它达到更高的级别（例如 65 个视频）时，它总是说 ffmpeg.exe 未找到，这是 ffmpeg 的问题吗？？无论如何，谢谢，origin whisper 只能一一转录，你的软件为我节省了很多时间。

**Comment by tigros** [comment]
stumbled on this error today, ffmpeg says "Duration: N/A" on corrupt files, wasn't aware of this.

So your 65th file is corrupt.

Updated v3.6 with this small fix.
