### ISSUE TITLE
【Bug】进度条Remaining在处理过程中一直都不动

### ISSUE THREAD

**Issue by kKevin0001** [tigros/Whisperer#85]
进度条在处理过程中长时间不动，已经处理了好几分钟，才显示进度条
建议在点击Go按钮之后就显示进度，这样更为友好
![image](https://github.com/user-attachments/assets/ae07b46a-abc4-41d5-a3fd-954078a83066)
![image](https://github.com/user-attachments/assets/bb5c8855-a08a-4572-aa87-202a8b22b3de)

**Comment by kKevin0001** [comment]
> that's normal, it has to get approximate speed judging from at least one completed file, so if you're converting only 1 file then no progress bar at all.

可以参考一下[WhisperDesktop](https://github.com/sakura6264/WhisperDesktop)的进度条吗？它从一开始处理就有进度显示

**Comment by tigros** [comment]
technical reasons, whisperer is running main.exe which doesn't report time remaining, whisperdesktop doesn't run external programs like that,, it's all in one, in C++, whisperer is C#.
