### ISSUE TITLE
What's the best model Whisperer can use?

### ISSUE THREAD

**Issue by RickArcher108** [tigros/Whisperer#87]
Hi Tigros. I'm still using ggml-large.bin. Is there a newer/better one I can be using?

**Comment by tigros** [comment]
i'm not aware of any, then again i didn't look. if anything does show up it would likely need to be tested by const-me and may require code changes, like v3 does.

**Comment by RickArcher108** [comment]
Hi Tigros. Nvidia just dropped an open-source [speech recognition model](https://huggingface.co/nvidia/parakeet-tdt-0.6b-v2) that can supposedly transcribe an hour of audio in a single second. Any chance you could incorporate this into Whisperer or develop something new that would give us batch processing and a GUI? Thanks.

**Comment by tigros** [comment]
Hiya!

So i tried it, large files are hopeless without a 100gb GPU, worked for smaller files, max about 20 mins on my RTX 3080 10gb.

Plus it's a monster to get going on windows, which isn't supported by nemo, the thing that makes use of parakeet-tdt-0.6b-v2.nemo

It's a massive pile of python, not going any further with it, sorry! Don't worry it wasn't all that fast either.. not for me anyway.

**Comment by RickArcher108** [comment]
Thanks for checking it out.
________________________________
