### ISSUE TITLE
Source mp3 is English/Franch/Japanese,how to Translate it to Chinese?

### ISSUE THREAD

**Issue by basicbh** [tigros/Whisperer#88]
and which model ?

Thanks!

**Comment by tigros** [comment]
you can simply set the language to Chinese and it will produce something, just not great. It's not supported, only translate to English is.

You should use large model v2, i tried base model a minute ago, totally bogus.

Happy new year!

**Comment by basicbh** [comment]
thank you tigros!god bless u ~
